feat(leet,scripts,global): kata

diff --git a/bin/global/leet b/bin/global/leet
--- a/bin/global/leet
+++ b/bin/global/leet
@@ -1,8 +1,8 @@
 #!/usr/bin/env sh
 
+PRACTICE_DIR="$HOME/Documents/github/temp/kata"
 DIRS="$HOME/Documents/github/leetcode
-$HOME/Documents/github/temp/leetcode-practice"
-PRACTICE_DIR="$HOME/Documents/github/temp/leetcode-practice"
+$PRACTICE_DIR"
 
 lower() {
   printf "%s" "$1" | tr '[:upper:]' '[:lower:]'
@@ -13,7 +13,7 @@ name() {
 }
 
 die() {
-  echo "$1" >&2
+  printf "%s\n" "$1" >&2
   exit 1
 }
 
@@ -41,27 +41,26 @@ get_index_type() {
 }
 
 open_index() {
-  file=$(get_index_type "$2") || die "cannot get the file type: $2"
+  file=$(get_index_type "$2") || die "cannot get file type: $2"
   tmux send-keys -t "$1" "LEETCODE=1 nvim $file" Enter
 }
 
-ensure_practice() {
-  [ -d "$PRACTICE_DIR" ] || mkdir -p "$PRACTICE_DIR" ||
-    die "cannot create directory: $PRACTICE_DIR"
+ensure_dir() {
+  [ -d "$1" ] || mkdir -p "$1" || die "cannot create directory: $1"
 }
 
 setup() {
   dir="$1"
   lang="$2"
   sname=$(name "$dir") || die "cannot derive name from: $dir"
-  new_session "$dir" || die "cannot create session: $sname"
-  [ "$sname" = "leetcode-practice" ] || return 0
+  new_session "$dir" || die "cannot create session for: $dir"
+  [ "$dir" = "$PRACTICE_DIR" ] || return 0
   new_window "$sname" "$dir" || die "cannot create window: $sname"
   open_index "$sname" "$lang" || die "cannot open index: $sname"
 }
 
 workspace() {
-  ensure_practice
+  ensure_dir "$PRACTICE_DIR"
   for dir in $DIRS; do
     setup "$dir" "$1"
   done
